from os.path import join
import pkg_resources


configfile: 'proj.config'


include: pkg_resources('ohsnap', 'snakemake/rules/codeml.rules')


rule all:
	input: all_files
	params: mem='1G', threads='1'
	log: join('logs', 'all.log')
		

